EmotionalIntelligenceTest/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EmotionalIntelligenceTest.Models
{
    [Table("Answers")]
    public partial class Answer
    {
       
        public int ID { get; set; }
        public string Content { get; set; }
        public bool correct { get; set; }
        public int QuestionID { get; set; }
        public virtual Question Question { get; set; }
    }
}

EmotionalIntelligenceTest/Models/ApplicationDBContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace EmotionalIntelligenceTest.Models
{
    public partial class ApplicationDBContext : DbContext
    {
        public ApplicationDBContext()
        {
        }

        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }

        //protected override void OnModelCreating(ModelBuilder modelBuilder)
        //{
        //    modelBuilder.Entity<Answer>().ToTable("Answers");
        //    modelBuilder.Entity<Question>().ToTable("Questions");
           
        //}
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var builder = new ConfigurationBuilder();
                builder.AddJsonFile("appsettings.json");
                var configuration = builder.Build();
                optionsBuilder.UseLazyLoadingProxies().UseSqlServer(configuration["connectionStrings:DefaultConnection"]);

            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Answer>(entity =>
            {
                entity.Property(e => e.ID)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Content)
                    .HasColumnName("content")
                    .HasColumnType("text");

                entity.Property(e => e.correct).HasColumnName("correct");

                entity.Property(e => e.QuestionID).HasColumnName("QuestionID");

                entity.HasOne(d => d.Question)
                    .WithMany(p => p.Answer)
                    .HasForeignKey(d => d.QuestionID)
                    .HasConstraintName("FK_Answers_Questions");
            });

            modelBuilder.Entity<Question>(entity =>
            {
                entity.Property(e => e.ID)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Content)
                    .HasColumnName("content")
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

EmotionalIntelligenceTest/Models/ErrorViewModel.cs
using System;

namespace EmotionalIntelligenceTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmotionalIntelligenceTest/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace EmotionalIntelligenceTest.Models
{
    [Table("Questions")]
    public class Question
    {
        public Question()
        {
            Answer = new HashSet<Answer>();
        }

        public int ID { get; set; }
        public string Content { get; set; }
        
        public byte[] image{ get; set; }
      
        public virtual ICollection<Answer> Answer { get; set; }
    }
}

EmotionalIntelligenceTest/Models/Seeder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmotionalIntelligenceTest.Models
{
    public class Seeder
    {
        private ApplicationDBContext _context;
        public Seeder(ApplicationDBContext context)
        {
            _context = context;
        }
        public void Seed()
        {


            _context.Database.EnsureCreated();
            if (_context.Questions.Any())
            {
                return;
            }
            var question = new Question[]
            {
                new Question{Content="This face is expressing?"},
                new Question{ Content="This face is expressing?"}

            };
            foreach (Question q in question)
            {
                _context.Questions.Add(q);
            }
            _context.AddRange();
            _context.SaveChanges();

            if (_context.Answers.Any())
            {
                return;
            }
            var answer = new Answer[]
            {
                new Answer{Content="sadness", correct=true, QuestionID=1 },
                new Answer{Content="amusement", correct=false, QuestionID=2 }
            };
            foreach (Answer a in answer)
            {
                _context.Answers.Add(a);
            }
            _context.AddRange();
            _context.SaveChanges();
        }




    }
}

EmotionalIntelligenceTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EmotionalIntelligenceTest.Models;

namespace EmotionalIntelligenceTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmotionalIntelligenceTest/Controllers/QuizsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmotionalIntelligenceTest.Models;
using Microsoft.AspNetCore.Http;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.VisualStudio.TestTools.UnitTesting;


namespace EmotionalIntelligenceTest.Controllers
{
    [TestClass]
    public class QuizsController : Controller
    {
        private  ApplicationDBContext _context = new ApplicationDBContext();

        public QuizsController(ApplicationDBContext context)
        {
           // _context = context;
        }

        //[Route("Index")]
        //[Route("")]
        //[Route("~/")]
        [TestMethod]
        public IActionResult Index()
        {
            ViewBag.Question = _context.Questions.ToList();

            return View();
        }

        [HttpPost]
        //[Route("submit")]
        public IActionResult Submit(IFormCollection iformcollection)
        {
           
            int score = 0;
            Byte[] img = null;
            string[] questionIds = iformcollection["QuestionID"];
            Assert.IsNotNull(questionIds);
            var question = _context.Questions.ToList() ;  
          foreach (var QuestionID in questionIds)
            {
                int answerIdCorrect = _context.Questions.Find(int.Parse
                    (QuestionID)).Answer.Where(a => a.correct == true).FirstOrDefault().ID;
                try
                {                   
                    if (answerIdCorrect == int.Parse(iformcollection["question_"+QuestionID]))
                    {
                        int id = Convert.ToInt32(QuestionID);
                        score++;
                        img = question[id - 1].image;
                        Assert.IsNotNull(img);

                        Image x = (Bitmap)new ImageConverter().ConvertFrom(img);
                        ViewBag.image = x;

                    }
                }
                catch(ArgumentNullException ex)
                {

                }
              
                ViewBag.Image = img;
                ViewBag.score = score;
            }
           
            return View("Result");
        }
    }
}

EmotionalIntelligenceTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Take a Greater Good Quiz!</h1>
        <button onclick="myFunction()">Take Quiz</button>
        <script>
            function myFunction() {
                location.replace("http://matchingskilllevel-dev.us-west-2.elasticbeanstalk.com/Quizs")
            }
        </script>
        @*<p>Learn about <a href="http://matchingskilllevel-dev.us-west-2.elasticbeanstalk.com/Quizs">building Web apps with ASP.NET Core</a>.</p>*@
    </div>

EmotionalIntelligenceTest/Views/Quizs/Create.cshtml
@*@model EmotionalIntelligenceTest.Models.Quiz

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Quiz</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option1" class="control-label"></label>
                <input asp-for="Option1" class="form-control" />
                <span asp-validation-for="Option1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option2" class="control-label"></label>
                <input asp-for="Option2" class="form-control" />
                <span asp-validation-for="Option2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option3" class="control-label"></label>
                <input asp-for="Option3" class="form-control" />
                <span asp-validation-for="Option3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option4" class="control-label"></label>
                <input asp-for="Option4" class="form-control" />
                <span asp-validation-for="Option4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="control-label"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorrectAns" class="control-label"></label>
                <input asp-for="CorrectAns" class="form-control" />
                <span asp-validation-for="CorrectAns" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

EmotionalIntelligenceTest/Views/Quizs/Delete.cshtml
@*@model EmotionalIntelligenceTest.Models.Quiz

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quiz</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorrectAns)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorrectAns)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>*@

EmotionalIntelligenceTest/Views/Quizs/Details.cshtml
@*@model EmotionalIntelligenceTest.Models.Quiz

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Quiz</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Option4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Option4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorrectAns)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorrectAns)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

EmotionalIntelligenceTest/Views/Quizs/Edit.cshtml
@*@model EmotionalIntelligenceTest.Models.Quiz

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Quiz</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option1" class="control-label"></label>
                <input asp-for="Option1" class="form-control" />
                <span asp-validation-for="Option1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option2" class="control-label"></label>
                <input asp-for="Option2" class="form-control" />
                <span asp-validation-for="Option2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option3" class="control-label"></label>
                <input asp-for="Option3" class="form-control" />
                <span asp-validation-for="Option3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Option4" class="control-label"></label>
                <input asp-for="Option4" class="form-control" />
                <span asp-validation-for="Option4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="control-label"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorrectAns" class="control-label"></label>
                <input asp-for="CorrectAns" class="form-control" />
                <span asp-validation-for="CorrectAns" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

EmotionalIntelligenceTest/Views/Quizs/Index.cshtml
@{
    Layout = null;
}
@{
    var endTime = DateTime.UtcNow.AddSeconds(65);
    var timeRemaining = TimeSpan.FromTicks(endTime.Ticks - DateTime.UtcNow.Ticks).TotalSeconds.ToString("#");
}
<style>
    #imgdiv {
        text-align: left;
    }
</style>
<!DOCTYPE html>

<html>
<head>
    @*<meta name="viewport"> content="width=device-width" />*@
    <title> Test Your Emotional Intelligence</title>
</head>
<body>
   <h2>Emotional Intelligence Quiz</h2>
    <h3>How well do you read other people?</h3>
    <form asp-controller="Quizs" asp-action="submit">
        <div>Time Remaining<b>: <span id="minRemaining" /></b>m<b>: <span id="secRemaining" /></b>s</div>
        <ol type="1">
            @foreach (var question in ViewBag.Question)
            {
                <li>

                    @question.Content
                    <input type="hidden" name="QuestionID" , value="@question.ID" />
                    <div id="imgdiv">
                        @{
                            var base64 = Convert.ToBase64String(question.image);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                            <img src="@imgSrc" width="150" height="150">
                        }

                    </div>

                    <ol type="a">
                        @foreach (var answer in question.Answer)
                        {

                            <li>
                                <input type="radio" class="rb" id="testRadio" name="question_@question.ID" value="@answer.ID" />
                                @answer.Content
                            </li>

                        }
                    </ol>
                </li>
            }
        </ol>
        <input type="submit" value="Submit" />
    </form>

</body>
</html>

<script>

    var remSeconds = @timeRemaining;
    var secondsCounter = remSeconds % 60;

    function formatNumber(number) {
        if (number < 10) return '0' + number;
        else return '' + number;
    }
    function startTick() {

        document.getElementById('secRemaining').innerText = formatNumber(secondsCounter);
        document.getElementById('minRemaining').innerText = parseInt(formatNumber(remSeconds / 60));
         var _tick = setInterval(function () {

            if (remSeconds > 0) {
                remSeconds = remSeconds - 1;
                secondsCounter = secondsCounter - 1;

                document.getElementById('secRemaining').innerText = formatNumber(secondsCounter);
                document.getElementById('minRemaining').innerText = parseInt(formatNumber(remSeconds / 60));

                if (secondsCounter == 0)
                    secondsCounter = 60;
            }
            else {
                alert('Your test time has expired');
                document.write("Your test time has expired, try again!");
                clearInterval(_tick);
                 location.reload();
                
                
            }
               
        }, 1000);
    }
    startTick();
</script>

EmotionalIntelligenceTest/Views/Quizs/Result.cshtml
@{
    ViewData["Title"] = "Result";
}

<!DOCTYPE html>

<html>
<head>
    <title>Please find the your score!!</title>
</head>
<body>
    <h3>Congratulations you've completed the test and your scores are:</h3>
    Score: @ViewBag.score
</body>
</html>

<div>
    <button onclick="goBack()">Re- take the test</button>
    </div>

<script>
function goBack() {
  window.history.back();
}
</script>

EmotionalIntelligenceTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test Your Emotional Intelligence</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Quizs" asp-action="Index">Test Your Emotional Intelligence</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-1">
              @*<li class="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Quizs" asp-action="Index">Test your intelligence</a>
              </li>*@
                @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Emotional Intelligence Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EmotionalIntelligenceTest/Views/_ViewImports1.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers